matrix:
  include:
    - language: objective-c
      osx_image: xcode10.2
      xcode_sdk: iphonesimulator12.2
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
      env: NODE_VERSION=10.15.3

      branches:
        only:
          - master

      cache: yarn

      install:
        - nvm --version
        - echo $NODE_VERSION
        - sudo launchctl limit maxfiles 2048 unlimited
        - sudo ulimit -n 10000
        - brew tap wix/brew
        - brew install applesimutils
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - brew install yarn --ignore-dependencies
        - npm install -g react-native-cli
        - npm install -g detox-cli
        - yarn
        - cd e2e
        - yarn
        - export PRODUCT_BUNDLE_IDENTIFIER="com.relicode.rn_gesture_handler_example"
        - detox build -c ios.sim.release > /dev/null
      script:
        - detox test -c ios.sim.release --no-color --headless --cleanup

    - language: android
      dist: trusty
      sudo: required
      jdk: oraclejdk8
      env: NODE_VERSION=10.15.3
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.yarn-cache
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
      install:
        - yes | sdkmanager "platforms;android-28"
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - node --version
        - npm install -g yarn
        - npm install -g react-native-cli
        - cd Example
        - yarn

      script:
        - cd ./android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug

    - language: objective-c
      osx_image: xcode10.2
      xcode_sdk: iphonesimulator12.2
      xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
      env: NODE_VERSION=10.15.3

      branches:
        only:
          - master

      cache: yarn

      install:
        - nvm --version
        - echo $NODE_VERSION
        - sudo launchctl limit maxfiles 2048 unlimited
        - sudo ulimit -n 10000
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - brew install yarn --ignore-dependencies
        - npm install -g react-native-cli
        - cd Example
        - yarn
        - export PRODUCT_BUNDLE_IDENTIFIER="com.relicode.rn_gesture_handler_example"

      script:
        - xcodebuild -project ./ios/GestureHandler.xcodeproj -scheme GestureHandler -configuration Debug -sdk iphonesimulator -derivedDataPath ./ios/build -UseModernBuildSystem=NO
